### ISSUE TITLE
Poetry books in open ebooks aren't classified as poetry

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/Simplified#52]
http://opds-browser-demo.herokuapp.com/?collection=https%3A%2F%2Fcirculation.openebooks.us%2Fsearch%2F%3Fq%3Dpoems

**Comment by leonardr** [comment]
This is yet another situation where the code we developed to classify 3M classifications falls short of being able to classify the full universe of BISAC classifications.
